apiVersion: v1
kind: Pod
metadata:
  name: demandagent
  labels:
    app: demand-agent
spec:
  #serviceAccountName: demand-agent-serviceaccount
  hostAliases:
    - ip: "172.16.40.21"
      hostnames:
      - "azuredevops.local"
  containers:
  - name: kubepodcreation
    image: matrek/demand-java-agent:1.0
    env:
      - name: AZP_URL
        valueFrom:
          secretKeyRef:
            name: azdevops
            key: AZP_URL
      - name: AZP_TOKEN
        valueFrom:
          secretKeyRef:
            name: azdevops
            key: AZP_TOKEN
      - name: AZP_POOL
        valueFrom:
          secretKeyRef:
            name: azdevops
            key: AZP_POOL
    #command: [ "/bin/sh", "-c", "--" ]
    #args: [ "while true; do sleep 30; done;" ]
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - "cat /azp/agent/_diag/Agent_*.log | grep \"Listening for Jobs\""
      initialDelaySeconds: 15
      periodSeconds: 5
  imagePullSecrets:
  - name: regcred
