apiVersion: apps/v1
kind: Deployment
metadata:
  name: init-agent
  namespace: az-devops
  labels:
    app: init-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: init-agent
  template:
    metadata:
      labels:
        app: init-agent
    spec:
      serviceAccountName: init-agent-serviceaccount
      hostAliases:
        - ip: "172.16.40.21"
          hostnames:
          - "azuredevops.local"
      containers:
      - name: kubepodcreation
        image: matrek/init-agent:1.0
        env:
          - name: AZP_URL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_URL
          - name: AZP_TOKEN
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_TOKEN
          - name: AZP_POOL
            valueFrom:
              secretKeyRef:
                name: azdevops
                key: AZP_POOL
        #command: [ "/bin/sh", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
      imagePullSecrets:
      - name: regcred
