apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: init-agent-rolebinding
  namespace: az-devops  # Replace with your desired namespace
subjects:
- kind: ServiceAccount
  name: init-agent-serviceaccount  # Replace with your ServiceAccount name
  namespace: az-devops  # Ensure this matches the namespace of the ServiceAccount
roleRef:
  kind: Role
  name: init-agent-role
  apiGroup: rbac.authorization.k8s.io